#!/bin/sh -e

# Move a conffile without triggering a dpkg question
mv_conffile() {
    local OLDCONFFILE="$1"
    local NEWCONFFILE="$2"

    [ -e "$OLDCONFFILE" ] || return 0

    echo "Preserving user changes to $NEWCONFFILE ..."
    mv -f "$NEWCONFFILE" "$NEWCONFFILE".dpkg-new
    mv -f "$OLDCONFFILE" "$NEWCONFFILE"
}

case "$1" in
configure)
    for item in config/environment.rb public; do
        chown -R root:www-data /usr/share/puppet-dashboard/${item}
	chmod 0640 /usr/share/puppet-dashboard/${item}
    done

    ln -sf /var/log/puppet-dashboard /usr/share/puppet-dashboard/log
    ln -sf /var/cache/puppet-dashboard /usr/share/puppet-dashboard/tmp/cache
    ln -s /var/lib/puppet-dashboard/* /usr/share/puppet-dashboard/tmp/
    ln -sf /var/run/puppet /usr/share/puppet-dashboard/tmp/pids

    if [ -f /usr/share/puppet-dashboard/config/database.yml ]; then
        mv_conffile "/usr/share/puppet-dashboard/config/database.yml" "/etc/puppet-dashboard/database.yml"
    fi
    
    if [ -f /usr/share/puppet-dashboard/config/settings.yml ]; then
        mv_conffile "/usr/share/puppet-dashboard/config/settings.yml" "/etc/puppet-dashboard/settings.yml"
    fi

    chown -R root:www-data /etc/puppet-dashboard/*.yml
    chmod -R o-rwx /etc/puppet-dashboard/*.yml

    if [ ! -h /usr/share/puppet-dashboard/config/database.yml ]; then
        ln -s /etc/puppet-dashboard/database.yml /usr/share/puppet-dashboard/config/database.yml
    fi
    
    if [ ! -h /usr/share/puppet-dashboard/config/settings.yml ]; then
        ln -s /etc/puppet-dashboard/settings.yml /usr/share/puppet-dashboard/config/settings.yml
    fi

    if [ ! -f /etc/nginx/sites-enabled/puppet-dashboard ]; then
	cp /usr/share/puppet-dashboard/config/puppet-dashboard.nginx /etc/nginx/sites-available/puppet-dashboard
	ln -s /etc/nginx/sites-available/puppet-dashboard /etc/nginx/sites-enabled/puppet-dashboard
   fi
esac

#DEBHELPER#
